#!/bin/bash

# this file gets modified when we run the program, but we don't want to keep the changes
git restore .googfiles/StoredCredential

git pull
echo
echo "Expect '[WARNING] Unrecognised tag: blocked' during build process"
echo
mvn package > build.out

if ! grep -q "BUILD SUCCESS" build.out; then
  echo failure
  exit 1
fi

# must restart all servers or you can get classnotfound errors

echo retarting tgserver
sudo systemctl restart tgserver
sleep 2
echo restarting hookserver
sudo systemctl restart hookserver
sleep 2
echo restarting mdserver
sudo systemctl restart mdserver
sleep 2
echo restarting fbserver
sudo systemctl restart fbserver
sleep 2
echo restarting refapi
sudo systemctl restart refapi
